@extends('errors.layout')
@section('title', ___('Page Not Found'))
@section('code', '404')
@section('message', ___('Page Not Found'))
@section('description', ___('The page you are looking for has not been found on our server.'))
