@extends('errors.layout')
@section('title', ___('Server Error'))
@section('code', '500')
@section('message', ___('Server Error'))
@section('description', ___("Sorry for the inconvenience, but we're working on it."))
